# Generated by Django 5.0.2 on 2024-02-22 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SocialDashboardAPI', '0003_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ScheduledPost',
        ),
    ]
